
### parameters

```{r}
setwd('D:\\datascienceCapstone\\nGramCreation')
library(dplyr)

# sample size
lang <- "en_US"
sampleSize <- "10"
testSize <- "0.02"
minOccurrencesUniGrams <- "01"
minOccurrences <- "1000"
```

### sampling + sentences tokenization

```{r}
source('./helpers/sampleCreator.R')
createSample(lang, sampleSize)
rm(createSample,createRawSample,tokenizeSent)
```

### unigrams tokenizing 
#   + cleaning (remove duplicates / identify non words as <unk>) 
#   + filtering (identify )words < minOccurrences as <unk>)

### fequency tables

```{r}
source('./helpers/unigramsCreator.R')
G1_list <- createUnigrams(lang, sampleSize, minOccurrences)
rm(createUnigrams,tokenize,cleanUnigrams,createIndex)

# frequency tables
source('./helpers/ngramFreqCreator.R')
nGramFreq <- getNgramFrequencies(G1_list,as.numeric(minOccurrences))
rm(getNgramFrequencies,getFrequencies)

# quick unigram frequency table
source('./helpers/dictCreator.R')
nGramFreq[["0"]] <- createDictList(nGramFreq[["1"]],1)

saveRDS(nGramFreq,paste0("../nGramFreq/",lang,".",sampleSize,".freq.",minOccurrences,".Rds"))
```


### mixed fequency tables

```{r}
source('./helpers/unigramsCreator.R')
G1_list <- createUnigrams(lang, sampleSize, minOccurrencesUniGrams)
rm(createUnigrams,tokenize,cleanUnigrams,createIndex)

# frequency tables
source('./helpers/ngramFreqCreator.R')
nGramFreq <- getNgramFrequencies(G1_list,as.numeric(minOccurrences))
rm(getNgramFrequencies,getFrequencies)

# quick unigram frequency table
source('./helpers/dictCreator.R')
nGramFreq[["0"]] <- createDictList(nGramFreq[["1"]],1)
  
saveRDS(nGramFreq,paste0("../nGramFreq/",lang,".",sampleSize,".freq.",minOccurrencesUniGrams,".",minOccurrences,".Rds"))
```


### test sampling + sentences tokenization

```{r}
source('./helpers/sampleCreator.R')
createSample(lang, sampleSize, testSize)
rm(createSample,createRawSample,tokenizeSent,sent_token_annotator)

source('./helpers/unigramsCreator.R')
G1_list <- createUnigrams(lang, sampleSize, minOccurrences,testSize)
rm(createUnigrams,tokenize,cleanUnigrams,createIndex,G1_list)
```


### dictionarize lists
```{r}
source('./helpers/dictCreator.R')
minOccurrences <- "10"
nGramFreq <- readRDS(paste0("../nGramFreq/",lang,".",sampleSize,".freq.",minOccurrences,".Rds"))

newNgramFreq <- list()
newNgramFreq[["0"]] <- createDictList(nGramFreq[["1"]],1)
newNgramFreq[["1"]] <- nGramFreq[["1"]][1:7,c("c2","score")]
newNgramFreq[["2"]] <- createValueList(nGramFreq[["2"]])
newNgramFreq[["3"]] <- createValueList(nGramFreq[["3"]])
newNgramFreq[["4"]] <- createValueList(nGramFreq[["4"]])

saveRDS(newNgramFreq,paste0("../nGramFreq/",lang,".",sampleSize,".freq.",minOccurrences,".fast.Rds"))
library(rjson)
freqJSON <- toJSON(nGramFreq)
write(freqJSON, paste0("../nGramFreq/",lang,".",sampleSize,".freq.",minOccurrences,".fast.json"))
```